name: X abc dns

on:
  schedule:
    - cron: '0 0 */1 * *'  # 每天凌晨运行一次，与24小时过期一致
  workflow_dispatch:  # 支持手动触发

permissions:
  contents: write  # 授予写入权限

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 指定具体版本以确保一致性

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiodns

      - name: Run script
        run: |
          python abc.py
        continue-on-error: false  # 如果脚本失败，工作流停止

     # - name: Run script
     #   run: |
     #     python generate_rules.py --force-refresh
     #   env:
     #     FORCE_REFRESH: true

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add a1.txt b1.txt a1b1.txt domain_cache.json
          git diff --staged --quiet || git commit -m "Update DNS rules - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
