name: Fetch Cloudflare Top 100 Domains CN

on:
  schedule:
    - cron: "0 4 * * *"  # UTC 04:00 = 北京时间 12:00 (UTC+8)
  workflow_dispatch:

jobs:
  fetch-and-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run fetch script
        run: python fetch_domains.py

      - name: List files for debugging
        run: ls -la

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add 100cn.txt || echo "No 100cn.txt file to add"
          git commit -m "Update 100cn.txt with latest Cloudflare Top 100 CN domains (${{ github.run_number }})" || echo "No changes to commit"
          git push
