# workflow名称
name: Update M3U # 修改名称

# 触发工作流的事件
on:
  # 定时触发：每小时执行一次
  schedule:
    - cron: '0 * * * *'
  # 允许手动从GitHub页面触发工作流
  workflow_dispatch:

# 定义工作流中的一个或多个作业 (jobs)
jobs:
  build:
    name: Filter and Update M3U Files # 修改作业名称

    # 授予写入仓库内容的权限
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 步骤4: 运行Python过滤脚本 (使用新的脚本文件名)
      - name: Run M3U filtering script
        run: python filter_m3u_two_files.py # 修改脚本文件名

      # 步骤5: 检查并自动提交更改
      # 这个action会自动提交 filter_m3u_two_files.py 生成的两个文件
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto update filtered m3u files" # 修改提交信息
          # 如果需要，可以明确指定提交的文件列表
          # files: |
          #   filtered_https_only.m3u
          #   filtered_http_only_valid.m3u
