name: Update Filtered M3U Playlists

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: Filter and Update M3U Files
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp

      - name: Create default config file
        run: |
          cat << EOF > config.json
          {
              "m3u_url": "https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u",
              "output_https": "filtered_https_only.m3u",
              "output_http_valid": "filtered_http_only_valid.m3u",
              "attributes_to_remove": ["tvg-logo"],
              "request_timeout": 5,
              "max_retries": 2,
              "retry_delay": 2,
              "max_workers": 10
          }
          EOF

      - name: Run M3U filtering script
        run: python filter_m3u_two_files.py --config config.json

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto update filtered M3U files"
          file_pattern: |
            filtered_https_only.m3u
            filtered_http_only_valid.m3u
