name: Update Cloudflare CN Top 100 Whitelist

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 每天中午 12:00 (CST, UTC+8) 运行
    # GitHub Actions 使用 UTC 时间, 12:00 CST = 04:00 UTC
    - cron: '0 4 * * *'

permissions:
  contents: write  # 允许推送更改
  
jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行环境

    steps:
      - name: Checkout repository # 步骤1：检出代码
        uses: actions/checkout@v4 # 使用官方的 checkout action

      - name: Set up Python # 步骤2：设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 指定 Python 版本

      - name: Install dependencies # 步骤3：安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # 从 requirements.txt 安装

      - name: Run script to generate whitelist # 步骤4：运行 Python 脚本
        run: python generate_whitelist.py

      - name: Commit and push if changed # 步骤5：提交并推送更改 (如果文件有变动)
        uses: stefanzweifel/git-auto-commit-action@v5 # 使用自动提交 action
        with:
          commit_message: "Update Cloudflare CN Top 100 Whitelist" # 提交信息
          file_pattern: 100cn.txt # 只监控这个文件的变化
          commit_options: '--no-verify' # 可选：跳过 pre-commit hooks (如果有)
          push_options: '--force' # 可选: 如果需要强制推送 (通常不推荐，但有时用于覆盖旧的自动提交)
          # 添加 Git 用户信息，以便 Action 可以提交
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
