name: X Filter
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # 手动触发
permissions:
  contents: write  # 允许写入仓库内容
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run merge script
        run: python xfilter.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add xfilter.txt requirements.txt
          # 检查是否有暂存的更改
          if ! git diff --staged --quiet; then
            # 如果有更改，则提交并推送
            git commit -m "Update merged adblock rules and dependencies"
            git push
          else
            # 如果没有更改，则打印消息
            echo "No changes to commit."
          fi
